### ISSUE TITLE
User Story 7, Review Statistics

### ISSUE THREAD

**Issue by mstang15** [StarPerfect/little_shop_1906#47]
```
As a visitor
When I visit an item's show page,
I see an area on the page for statistics about reviews:
- the top three reviews for this item (title and rating only)
- the bottom three reviews for this item  (title and rating only)
- the average rating of all reviews for this item
```

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is tested in development
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #88

child of #93

**Comment by MackHalliday** [comment]
Reopening, added additional testing for review model and updated active records methods. 

Code needs review and pull request for user_story_7 submitted
